// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svryinwtaczwndeqwyvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2cnlpbnd0YWN6d25kZXF3eXZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MTI1NzEsImV4cCI6MjA2NzE4ODU3MX0.fYjWj7doMSZkioISqPIgqI5FF4I90wCioh0-SqrKst8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});